### ISSUE TITLE
Other Vision Models

### ISSUE THREAD

**Issue by Swaggeroo** [Swaggeroo/obsidian-ai-image-analyzer#1]
Support other vision models like

https://ollama.com/library/llava-llama3
https://ollama.com/library/llava-phi3
https://ollama.com/library/moondream

or other parameters from https://ollama.com/library/llava like 13B or 34B

A change of a model should clear the cache

**Comment by Cammagno** [comment]
"A change of a model should clear the cache"

Set on by default but optionally, please.

**Comment by Swaggeroo** [comment]
Implemented with [Release 0.1.6](https://github.com/Swaggeroo/obsidian-ai-image-analyzer/releases/tag/0.1.6)
