### ISSUE TITLE
Failed to pull ${model.name} model.

### ISSUE THREAD

**Issue by cybaea** [Swaggeroo/obsidian-ai-image-analyzer#55]
When I try to pull the default model, I get an error: `Failed to pull ${model.name} model` I installed from the community plugins.

It is not obvious what is the fix I need to apply here?

![image](https://github.com/user-attachments/assets/b9c0c7db-a2b0-4623-9a71-f581cdb8e752)

**Comment by cybaea** [comment]
This is version 0.1.10

**Comment by Swaggeroo** [comment]
Could you press `ctrl + shift + I`  and send the Output of the console here?

**Comment by cybaea** [comment]
Error message was that it couldn't communicate with server. I re-installed Ollama and now it is working. Thank you for your help!
